// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_test_leaderboard_a = "CgkIs4aK15UaEAIQBg"; // <GPGSID>
        public const string leaderboard_test_leaderboard_b = "CgkIs4aK15UaEAIQDA"; // <GPGSID>
        public const string event_test_event = "CgkIs4aK15UaEAIQDQ"; // <GPGSID>
        public const string quest_test_quest = "CgkIs4aK15UaEAIQDg"; // <GPGSID>
        public const string achievement_incremental_achievement_a = "CgkIs4aK15UaEAIQBw"; // <GPGSID>
        public const string achievement_incremental_achievement_b = "CgkIs4aK15UaEAIQCA"; // <GPGSID>
        public const string achievement_incremental_achievement_c = "CgkIs4aK15UaEAIQCQ"; // <GPGSID>
        public const string achievement_incremental_achievement_d = "CgkIs4aK15UaEAIQCg"; // <GPGSID>
        public const string achievement_unlockable_achievement_a = "CgkIs4aK15UaEAIQAQ"; // <GPGSID>
        public const string achievement_unlockable_achievement_b = "CgkIs4aK15UaEAIQAg"; // <GPGSID>
        public const string achievement_unlockable_achievement_c = "CgkIs4aK15UaEAIQAw"; // <GPGSID>
        public const string achievement_unlockable_achievement_d = "CgkIs4aK15UaEAIQBA"; // <GPGSID>
        public const string achievement_unlockable_achievement_e = "CgkIs4aK15UaEAIQBQ"; // <GPGSID>

}

